### PR TITLE
Add feature force-fallback

### LINKED ISSUE #216: Add feature for force not(wrap_proc_macro)
I would like to be able to force the use of the [fallback implementation](https://github.com/alexcrichton/proc-macro2/blob/master/src/lib.rs#L104) even if I am in a proc_macro environment. 

I use `span-locations` feature and emit errors manually and it hinders me because the behavior in the libraries coverage differs from that in proc_macro. 

Like behavior of this [fork](https://github.com/botika/proc-macro2-impersonated), to be able to do [this](https://github.com/botika/yarte/tree/master/yarte/tests/fails) in a proc_macro context in templates (`hbs` external files). Only need a feature and one method like [this](https://github.com/botika/proc-macro2-impersonated/blob/master/tests/test.rs#L276-L288). 

I can implement it.

Could we add this feature?

### PR DESCRIPTION
**Pull request by botika**
Closes #216

### CODE REVIEW

**Comment by botika** [comment]
I use it within syn. 

So, should we implement some solution to force use the fallback in `syn`?

**Comment by dtolnay** [comment]
Could you confirm that #220 resolves your use case?

**Comment by botika** [comment]
Yes, it is solved.

I use it in [yarte](https://github.com/botika/yarte), and it read external templates, I will use this feature and span-locations, along with my own version of Span to issue diagnoses very similar to those of rustc

**Comment by botika** [comment]
Yes, it would be solved.

Thanks!!

**Pull request closed without merging**
