### PR TITLE
added public function to check if it's a valid identifier

### PR DESCRIPTION
**Pull request by Volker-Weissmann**
I added a public function to check if a string is a valid identifier.

### CODE REVIEW

**Review by dtolnay — COMMENTED** [review]
Thanks for the PR!

I think I would prefer not to expose this.

Here is a more compact implementation if you need one to copy into your project:

```rust
pub fn valid_ident(input: &str) -> bool {
    let mut chars = input.chars();
    chars.next().map_or(false, |first| {
        (unicode_xid::UnicodeXID::is_xid_start(first) || first == '_')
            && chars.all(unicode_xid::UnicodeXID::is_xid_continue)
    })
}
```

**Comment by Volker-Weissmann** [comment]
> I think I would prefer not to expose this.

Why not? Otherwise, we have a function (Ident::new) that can panic, but there is no way of knowing if it will panic. note that the the rules what is a valid identifier and what is not a valid identifier do not have to be stabe in order for us to expose the valid_ident function.

**Comment by dtolnay** [comment]
This crate just mirrors the API of libproc_macro. Unless something is inapplicable to libproc_macro for some reason, the place to propose it is upstream.

**Comment by Volker-Weissmann** [comment]
ok

**Pull request closed without merging**
