### PR TITLE
Enable rich API on 1.29.0

### PR DESCRIPTION
**Pull request by dtolnay**
This is stabilizing next week!

### CODE REVIEW

**Comment by alexcrichton** [comment]
Sounds good to me! r=me with green CI and all that

**Comment by dtolnay** [comment]
The failure was in `RUSTFLAGS='--cfg procmacro2_semver_exempt' cargo +beta test`. I removed that from CI because semver exempt tracks whatever is in nightly.

**Comment by alexcrichton** [comment]
Could the CI be updated to only pass that flag on nightly? That definitely makes sense to me that it should only be nightly!

**Comment by dtolnay** [comment]
I removed that only from the beta build, it continues to be tested on the nightly build. :)

**Comment by alexcrichton** [comment]
Oh right yeah, but I think it's still tested for 1.15.0/stable (which means our CI will break for the 1.29.0 stable release in theory)

**Pull request merged**
