### PR TITLE
Add From<proc_macro::Span> for proc_macro2::Span.

### PR DESCRIPTION
**Pull request by SergioBenitez**
We have one direction now. This adds the other.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! I wonder if this should perhaps have a dedicated method name, like `from_unstable` though?

**Comment by mystor** [comment]
Yeah, I don't think this needs to be a trait, I think it'd be better to have a dedicated method for this.

**Comment by SergioBenitez** [comment]
Either is fine, I suppose. I don't see the benefit in making this a separate method. I like the terseness of being able to call `.into()`.

**Comment by SergioBenitez** [comment]
@dtolnay I store `proc_macro::Span`'s in most of my implementations data structures since I use the `proc_macro` APIs, but I occasionally need to interface them with `syn` and `quote` which require `proc_macro2::Span`'s, of course.

**Comment by alexcrichton** [comment]
Ok let's go for it and see how it goes!

**Pull request merged**
